{% set pyproject = load_file_data('pyproject.toml') %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}

package:
  name: {{ poetry.get('name') }}
  version: {{ poetry.get('version') }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

about:
  home: {{ poetry.get('homepage') }}
  license: {{ poetry.get('license') }}
  license_file: LICENSE
  license_url: https://github.com/NiaOrg/NiaPy/blob/master/LICENSE
  summary: {{ poetry.get('description') }}
  doc_url: {{ poetry.get('documentation') }}
  dev_url: {{ poetry.get('repository') }}