name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  osx_10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_osx.sh
  windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: .\tools\gha_windows-2019.ps1
        shell: powershell
  build-and-deploydocs:
    if: ${{ github.event_name }} == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build 🔧
        run: bash tools/gha_deploydocs.sh
      - name: Upload to github pages 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/sphinx/_build/html # The folder the action should deploy.
