from .problems.Sphere import Sphere
from .problems.SumOfSquares import SumOfSquares
from .problems.Schwefel12 import Schwefel12
from .problems.Rastrigin import Rastrigin
from .problems.Ackley import Ackley
from .problems.Griewank import Griewank
from .problems.Rosenbrock import Rosenbrock
from .problems.Shekelfoxholes import Shekelfoxholes
from .problems.SixHumpCamelBack import SixHumpCamelBack
from .problems.Branin import Branin