# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  manylinux228-py311:
     runs-on: ubuntu-latest
     container:
      image: pagmo2/manylinux228_x86_64_with_deps:latest
      env: 
        PYGMO_BUILD_TYPE: "Python311"
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
     steps:
       - uses: actions/checkout@v2
       - name: Build
         run: bash tools/gha_manylinux.sh
  manylinux228-py310:
     runs-on: ubuntu-latest
     container:
      image: pagmo2/manylinux228_x86_64_with_deps:latest
      env: 
        PYGMO_BUILD_TYPE: "Python310"
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
     steps:
       - uses: actions/checkout@v2
       - name: Build
         run: bash tools/gha_manylinux.sh
  manylinux228-py39:
     runs-on: ubuntu-latest
     container:
      image: pagmo2/manylinux228_x86_64_with_deps:latest
      env: 
        PYGMO_BUILD_TYPE: "Python39"
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
     steps:
       - uses: actions/checkout@v2
       - name: Build
         run: bash tools/gha_manylinux.sh
  manylinux228-py38:
     runs-on: ubuntu-latest
     container:
      image: pagmo2/manylinux228_x86_64_with_deps:latest
      env: 
        PYGMO_BUILD_TYPE: "Python38"
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
     steps:
       - uses: actions/checkout@v2
       - name: Build
         run: bash tools/gha_manylinux.sh
  macos-10_15-py310:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_macos-10.15-py310.sh
  windows-2019-py311:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: .\tools\gha_windows.ps1
        shell: powershell
  build-and-deploydocs:
    if: ${{ github.event_name }} == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build 🔧 
        run: bash tools/gha_deploydocs.sh
      - name: Upload to github pages 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_build/html # The folder the action should deploy.

  
